<a href="https://colab.research.google.com/github/LeoFernanndes/notebooks/blob/master/MLAZ_Artificial_Neural_Network_Churn_Modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Data preprocessing

### Importing dataset

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf


url = "https://raw.githubusercontent.com/LeoFernanndes/ML-A-a-Z/master/Part%208%20-%20Deep%20Learning/Section%2039%20-%20Artificial%20Neural%20Networks%20(ANN)/Python/Churn_Modelling.csv"
df = pd.read_csv(url)
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [7]:
# splitting data without concerning about suffleness
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

In [10]:
from sklearn.preprocessing import LabelEncoder


# encoding gender data
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough")
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


### Splitting data into train and test

In [17]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Feature scaling

In [19]:
from sklearn.preprocessing import StandardScaler


sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

## 2. Building the neural net

In [22]:
nn = tf.keras.models.Sequential()
nn.add(tf.keras.layers.Dense(units=6, activation="relu")) # input layer
nn.add(tf.keras.layers.Dense(units=6, activation="relu")) # hidden layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid")) # output layer
nn.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

## 3. Training the nn

In [23]:
nn.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6521 - accuracy: 0.6435
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4832 - accuracy: 0.7976
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4501 - accuracy: 0.8025
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4365 - accuracy: 0.8064
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4284 - accuracy: 0.8074
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4215 - accuracy: 0.8117
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4136 - accuracy: 0.8176
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4058 - accuracy: 0.8209
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3975 - accuracy: 0.8231
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3891 - accura

## 4. Making and evaluating predictions

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score


y_pred = nn.predict(X_test)
y_pred = np.array(y_pred > 0.5) # converting continous output from sigmoid to discrete prediction
y_pred = [1 if element == True else 0 for element in y_pred]


cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1555   52]
 [ 232  161]]


0.858